name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests --all-features
      run: cargo test --verbose
    - name: Run bench --all-features
      run: cargo bench --verbose
    - name: Run fmt
      run: cargo fmt -- --check
      
